# Generated by Django 3.2.8 on 2021-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlphavantageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('close_value', models.FloatField()),
                ('high_value', models.FloatField()),
                ('created_time', models.DateTimeField()),
                ('volume_value', models.IntegerField()),
            ],
        ),
    ]
